---
- name: apache web server
  hosts: servers
  become: yes
  any_errors_fatal: yes
  roles:
    - myapache

- name: load balancer
  hosts: load_balancer
  become: true
  any_errors_fatal: yes
  roles:
    - myloadbalancer
